### ISSUE TITLE
Question about usecase

### ISSUE THREAD

**Issue by MostHated** [ryanslikesocool/Shapes#1]
Hey there,
    I have been looking around for something performant that could replace using the standard Gizmo drawing for some of my tools and thought this looked quite interesting. I am trying to decide if it might work for my use case, though. You can see some of the things I am currently visualizing below, I am wondering if what I am doing would even be ideal for this system, though. It looks like this package requires scene objects, and with the large amount of drawing I am doing, if I need an object for each, it probably won't be doable, but I just wanted to get your quick opinion to see if it would be worth taking a dive into this or not. 

Whether I use it for this particular thing or not, I can definitely see a lot of places this will be useful though, so thanks for sharing it. :+1: 

Thanks,
-MH 

<details>
<summary>Example1</summary>

![](https://i.imgur.com/rVxduWo.png)

</details>

<details>
<summary>Example2</summary>

![](https://i.imgur.com/uK4De3P.png)

</details>

<details>
<summary>Example3</summary>

![](https://i.imgur.com/798xJQj.png)

</details>

**Comment by ryanslikesocool** [comment]
The way that mesh points are calculated (with Jobs and the Burst Compiler) is very performant.  _However_, the way shapes are rendered with this package is not performant right now (no _true_ immediate mode, just technically rendering in immediate mode).

If I'm understanding correctly, the main problem is rendering time.  If that's the case, I'd recommend taking a look at [Shapes](https://assetstore.unity.com/packages/tools/particles-effects/shapes-173167) by Freya Holmér.  Shapes has an (actual) immediate mode feature, so depending on the order you draw the lines, you can probably get at least every single line of the same color done in a single draw call, which is still much better than Unity's probably doing.

**Comment by MostHated** [comment]
Ah, I understand. I actually have Shapes, but like most of the assets I own, I can't really use it as I eventually want to share the package on GitHub and hate having a paid dependency. It's not really a huge deal, I just am always on the lookout for drawing packages I have not tested yet, just in case I eventually find "the one", lol.  I appreciate the info, thanks again.
